### ISSUE TITLE
Error importing template on Zabbix 6.4.14

### ISSUE THREAD

**Issue by jeroenvermeulen** [zabbix-tooling/zabbix-agent-extensions#42]
I tried to import `zabbix_templates/6.4/custom-os-linux.xml` from release `zabbix-agent-extensions-2.6.3` and from the `master` branch.

## Error 1:
`Invalid parameter "/1/request_method": value must be 0.`
Found a [fix](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/461658-error-importing-template).

## Error 2:
`Invalid parameter "/27/trapper_hosts": value must be empty.`
Found a [fix](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/467335-import-template-failed-from-old-zabbix-version?p=473402#post473402)

## Solution
After patching the files this way:
```
cat custom-os-linux.xml | grep -Ev '<(request_method|allowed_hosts)>' > custom-os-linux__fix.xml
cat custom-os-linux-hardware.xml | grep -v '<request_method>' > custom-os-linux-hardware__fix.xml
cat custom-os-puppet.xml | grep -v '<request_method>' > custom-os-puppet__fix.xml
cat custom-service-apache.xml | grep -v '<request_method>' > custom-service-apache__fix.xml
cat custom-service-nginx.xml | grep -v '<request_method>' > custom-service-nginx__fix.xml
cat custom-service-springboot.xml | grep -v '<request_method>' > custom-service-springboot__fix.xml
cat custom-service-varnish.xml | grep -Ev '<(request_method|allowed_hosts)>' > custom-service-varnish__fix.xml
```
I could import the files.

**I think it would be good to make the templates suitable for the latest stable Zabbix.**

**Comment by jeroenvermeulen** [comment]
I could make a PR but I don't know if it has no side effects for older versions to remove all `<request_method>` and `<allowed_hosts>` tags. Is it true we shouldn't include these tags since Zabbix 6.14 ?

**Comment by scoopex** [comment]
Yes, this should work. A PR would be great!
