### ISSUE TITLE
vfs.dev.discovery is replaced but does not match original output

### ISSUE THREAD

**Issue by jeroenvermeulen** [zabbix-tooling/zabbix-agent-extensions#46]
zabbix-agent-extensions replaces the default `vfs.dev.discovery` by `custom.vfs.dev.discovery` using [an Alias](https://github.com/zabbix-tooling/zabbix-agent-extensions/blob/master/extension-files/agent-config/zabbix_disk_discovery.conf#L4)
However the output from the command used for `custom.vfs.dev.discovery` does not return the expected macros `{#DEVNAME}` and `{#DEVTYPE}`.
```
/usr/bin/zabbix_discovery_devices --config /etc/zabbix/item_zabbix_discovery_devices.json
```
Returns something like:
```
[
   { 
      "{#BLOCKDEVICE}":"sda"
   }
]

```
While according to [the Zabbix manual](https://www.zabbix.com/documentation/6.4/en/manual/discovery/low_level_discovery/examples/devices?hl=vfs.dev.discovery)
it should look like this:
```
[
   { 
      "{#DEVNAME}":"sda",
      "{#DEVTYPE}":"disk"
   },
   { 
      "{#DEVNAME}":"sda1",
      "{#DEVTYPE}":"partition"
   }
]
```

**Comment by jeroenvermeulen** [comment]
Do we still need to override the default `vfs.dev.discovery`?
Or can we maybe just remove [this line](https://github.com/zabbix-tooling/zabbix-agent-extensions/blob/master/extension-files/agent-config/zabbix_disk_discovery.conf#L4):
```
Alias=vfs.dev.discovery:custom.vfs.dev.discovery
```

**Comment by scoopex** [comment]
I think we still need it, because this script provides extra functionalities.
See: `./zabbix_discovery_devices --help`
